project: x77
queue: normal
ncpus: 1756
jobfs: 10GB

walltime: 02:00:00
jobname: OM4_025.JRA

shortpath: /scratch/x77

model: mom6
exe: /scratch/x77/ahg157/mom6/bin/MOM6-panan
input: OM4_025.JRA

collate: false
runlog: false
storage:
  gdata:
    - ua8
    - x77

mpi:
    module: openmpi/4.0.3

